### PR TITLE
optimize sample.pdf speed

### PR DESCRIPTION
**Pull request by benoit-pierre**
For speed of processing by the testsuite: update some pages (9-14 & 34) to avoid JBIG2 image compression (slow) at the cost of a bigger file.

- - -
This change is [Reviewable](https://reviewable.io/reviews/koreader/test-data/1)

### CODE REVIEW

**Comment by Frenzie** [comment]
Do the base tests still include JBIG2?

**Comment by benoit-pierre** [comment]
Yes:
```lua
spec/unit/mupdf_spec.lua
9:local jbig2_pdf = "spec/base/unit/data/2col.jbig2.pdf"
29:    it("should render jbig2 PDFs", function()
30:        local doc = M.openDocument(jbig2_pdf)
```

**Comment by benoit-pierre** [comment]
Before:
```
mutool info -I sample.pdf:

PDF-1.6
Info object (378 0 R):
<</ModDate(D:20140516224813+08'00')/CreationDate(D:20140516224813+08'00')/Creator(pdftk 2.01 - www.pdftk.com)/Producer(itext-paulo-155 \(itextpdf.sf.net-lowagie.com\))>>
Pages: 45

Retrieving info from pages 1-45...
Images (48):
	1	(3 0 R):	[ JBIG2 ] 3658x5357 1bpc DevGray (4 0 R)
	2	(7 0 R):	[ JBIG2 ] 3658x5357 1bpc DevGray (10 0 R)
	3	(13 0 R):	[ JBIG2 ] 2512x4168 1bpc DevGray (14 0 R)
	4	(18 0 R):	[ JBIG2 ] 2512x4168 1bpc DevGray (19 0 R)
	5	(23 0 R):	[ JBIG2 ] 2512x4168 1bpc DevGray (24 0 R)
	6	(28 0 R):	[ JBIG2 ] 2512x4168 1bpc DevGray (29 0 R)
	7	(33 0 R):	[ JBIG2 ] 2512x4168 1bpc DevGray (34 0 R)
	8	(38 0 R):	[ JBIG2 ] 2512x4168 1bpc DevGray (39 0 R)
	9	(43 0 R):	[ JPX ] 2112x3470 8bpc DevRGB (45 0 R)
	9	(43 0 R):	[ JPX ] 704x1157 8bpc DevRGB (47 0 R)
	10	(50 0 R):	[ JPX ] 2112x3470 8bpc DevRGB (51 0 R)
	10	(50 0 R):	[ JPX ] 704x1157 8bpc DevRGB (53 0 R)
	11	(56 0 R):	[ JPX ] 2112x3470 8bpc DevRGB (57 0 R)
	11	(56 0 R):	[ JPX ] 704x1157 8bpc DevRGB (59 0 R)
	12	(62 0 R):	[ JPX ] 2112x3470 8bpc DevRGB (63 0 R)
	12	(62 0 R):	[ JPX ] 704x1157 8bpc DevRGB (65 0 R)
	13	(68 0 R):	[ JPX ] 2112x3470 8bpc DevRGB (69 0 R)
	13	(68 0 R):	[ JPX ] 704x1157 8bpc DevRGB (71 0 R)
	14	(74 0 R):	[ JPX ] 2112x3470 8bpc DevRGB (75 0 R)
	14	(74 0 R):	[ JPX ] 704x1157 8bpc DevRGB (77 0 R)
	15	(80 0 R):	[ JBIG2 ] 2556x3832 1bpc DevGray (83 0 R)
	16	(86 0 R):	[ JBIG2 ] 2556x3832 1bpc DevGray (87 0 R)
	17	(90 0 R):	[ JBIG2 ] 2556x3832 1bpc DevGray (92 0 R)
	18	(95 0 R):	[ JBIG2 ] 2556x3832 1bpc DevGray (97 0 R)
	25	(220 0 R):	[ JBIG2 ] 1640x2491 1bpc ImageMask (221 0 R)
	26	(225 0 R):	[ JBIG2 ] 1640x2491 1bpc ImageMask (226 0 R)
	27	(229 0 R):	[ JBIG2 ] 1640x2491 1bpc ImageMask (230 0 R)
	28	(233 0 R):	[ JBIG2 ] 1640x2491 1bpc ImageMask (234 0 R)
	29	(237 0 R):	[ JBIG2 ] 1640x2491 1bpc ImageMask (238 0 R)
	30	(241 0 R):	[ JBIG2 ] 3798x5184 1bpc DevGray (248 0 R)
	31	(251 0 R):	[ JBIG2 ] 3856x5284 1bpc DevGray (257 0 R)
	32	(260 0 R):	[ JBIG2 ] 3783x5163 1bpc DevGray (264 0 R)
	33	(267 0 R):	[ JBIG2 ] 3867x5299 1bpc DevGray (268 0 R)
	34	(271 0 R):	[ JPX ] 547x340 8bpc DevCMYK (291 0 R)
	34	(271 0 R):	[ JPX ] 547x323 8bpc DevCMYK (292 0 R)
	34	(271 0 R):	[ JPX ] 324x47 8bpc DevCMYK (293 0 R)
	35	(305 0 R):	[ JPX ] 1134x1411 8bpc DevCMYK (310 0 R)
	36	(313 0 R):	[ JPX ] 726x296 8bpc DevCMYK (321 0 R)
	36	(313 0 R):	[ JPX ] 1314x353 8bpc DevCMYK (322 0 R)
	37	(329 0 R):	[ JPX ] 1161x712 8bpc DevGray (331 0 R)
	38	(336 0 R):	[ JPX ] 740x452 8bpc DevCMYK (338 0 R)
	39	(341 0 R):	[ JPX ] 1179x620 8bpc DevCMYK (343 0 R)
	40	(346 0 R):	[ CCITTFax ] 1632x2400 1bpc ImageMask (348 0 R)
	41	(352 0 R):	[ CCITTFax ] 1632x2400 1bpc ImageMask (354 0 R)
	42	(357 0 R):	[ CCITTFax ] 1632x2400 1bpc ImageMask (359 0 R)
	43	(362 0 R):	[ CCITTFax ] 1632x2400 1bpc ImageMask (364 0 R)
	44	(367 0 R):	[ CCITTFax ] 1632x2400 1bpc ImageMask (369 0 R)
	45	(372 0 R):	[ CCITTFax ] 1632x2400 1bpc ImageMask (374 0 R)

```

After:
```
mutool info -I sample.pdf:

PDF-1.7

Pages: 45

Retrieving info from pages 1-45...
Images (49):
	1	(4 0 R):	[ JBIG2 ] 3658x5357 1bpc DevGray (3 0 R)
	2	(8 0 R):	[ JBIG2 ] 3658x5357 1bpc DevGray (7 0 R)
	3	(11 0 R):	[ JBIG2 ] 2512x4168 1bpc DevGray (9 0 R)
	4	(14 0 R):	[ JBIG2 ] 2512x4168 1bpc DevGray (12 0 R)
	5	(17 0 R):	[ JBIG2 ] 2512x4168 1bpc DevGray (15 0 R)
	6	(20 0 R):	[ JBIG2 ] 2512x4168 1bpc DevGray (18 0 R)
	7	(23 0 R):	[ JBIG2 ] 2512x4168 1bpc DevGray (21 0 R)
	8	(26 0 R):	[ JBIG2 ] 2512x4168 1bpc DevGray (24 0 R)
	9	(30 0 R):	[ DCT ] 704x1157 8bpc DevRGB (29 0 R)
	9	(30 0 R):	[ DCT ] 2112x3470 8bpc DevRGB (27 0 R)
	10	(34 0 R):	[ DCT ] 704x1157 8bpc DevRGB (33 0 R)
	10	(34 0 R):	[ DCT ] 2112x3470 8bpc DevRGB (31 0 R)
	11	(38 0 R):	[ DCT ] 704x1157 8bpc DevRGB (37 0 R)
	11	(38 0 R):	[ DCT ] 2112x3470 8bpc DevRGB (35 0 R)
	12	(42 0 R):	[ DCT ] 704x1157 8bpc DevRGB (41 0 R)
	12	(42 0 R):	[ DCT ] 2112x3470 8bpc DevRGB (39 0 R)
	13	(46 0 R):	[ DCT ] 704x1157 8bpc DevRGB (45 0 R)
	13	(46 0 R):	[ DCT ] 2112x3470 8bpc DevRGB (43 0 R)
	14	(50 0 R):	[ DCT ] 704x1157 8bpc DevRGB (49 0 R)
	14	(50 0 R):	[ DCT ] 2112x3470 8bpc DevRGB (47 0 R)
	15	(53 0 R):	[ JBIG2 ] 2556x3832 1bpc DevGray (52 0 R)
	16	(55 0 R):	[ JBIG2 ] 2556x3832 1bpc DevGray (54 0 R)
	17	(58 0 R):	[ JBIG2 ] 2556x3832 1bpc DevGray (57 0 R)
	18	(61 0 R):	[ JBIG2 ] 2556x3832 1bpc DevGray (60 0 R)
	25	(157 0 R):	[ JBIG2 ] 1640x2491 1bpc ImageMask (155 0 R)
	26	(159 0 R):	[ JBIG2 ] 1640x2491 1bpc ImageMask (158 0 R)
	27	(161 0 R):	[ JBIG2 ] 1640x2491 1bpc ImageMask (160 0 R)
	28	(163 0 R):	[ JBIG2 ] 1640x2491 1bpc ImageMask (162 0 R)
	29	(165 0 R):	[ JBIG2 ] 1640x2491 1bpc ImageMask (164 0 R)
	30	(173 0 R):	[ JBIG2 ] 3798x5184 1bpc DevGray (172 0 R)
	31	(176 0 R):	[ JBIG2 ] 3856x5284 1bpc DevGray (175 0 R)
	32	(178 0 R):	[ JBIG2 ] 3783x5163 1bpc DevGray (177 0 R)
	33	(180 0 R):	[ JBIG2 ] 3867x5299 1bpc DevGray (179 0 R)
	34	(215 0 R):	[ DCT ] 324x47 8bpc DevCMYK (198 0 R)
	34	(215 0 R):	[ DCT ] 547x323 8bpc DevCMYK (197 0 R)
	34	(215 0 R):	[ DCT ] 547x340 8bpc DevCMYK (196 0 R)
	35	(241 0 R):	[ JPX ] 1134x1411 8bpc DevCMYK (231 0 R)
	36	(257 0 R):	[ JPX ] 1314x353 8bpc DevCMYK (252 0 R)
	36	(257 0 R):	[ JPX ] 726x296 8bpc DevCMYK (251 0 R)
	37	(261 0 R):	[ JPX ] 1161x712 8bpc DevGray (258 0 R)
	38	(267 0 R):	[ JPX ] 324x47 8bpc DevCMYK (266 0 R)
	38	(267 0 R):	[ JPX ] 740x452 8bpc DevCMYK (265 0 R)
	39	(269 0 R):	[ JPX ] 1179x620 8bpc DevCMYK (268 0 R)
	40	(272 0 R):	[ CCITTFax ] 1632x2400 1bpc ImageMask (270 0 R)
	41	(274 0 R):	[ CCITTFax ] 1632x2400 1bpc ImageMask (273 0 R)
	42	(276 0 R):	[ CCITTFax ] 1632x2400 1bpc ImageMask (275 0 R)
	43	(278 0 R):	[ CCITTFax ] 1632x2400 1bpc ImageMask (277 0 R)
	44	(280 0 R):	[ CCITTFax ] 1632x2400 1bpc ImageMask (279 0 R)
	45	(282 0 R):	[ CCITTFax ] 1632x2400 1bpc ImageMask (281 0 R)

```

**Review by Frenzie — APPROVED** [review]

**Comment by Frenzie** [comment]
@NiLuJe Fine by you?

**Comment by NiLuJe** [comment]
Yup! (had a very quick glance at the rest of the series, nothing jumped out either ;)). 👍

**Pull request merged**
